// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package query

import (
	"time"

	"github.com/google/uuid"
)

type DeletedRecord struct {
	ID          uuid.UUID
	DeletedAt   time.Time
	SourceTable string
	SourceID    string
	Data        []byte
}

type DisallowToken struct {
	TokenID   uuid.UUID
	CreatedAt time.Time
}

type OpenidNonce struct {
	ID          int32
	CreatedAt   time.Time
	Endpoint    string
	NonceTime   time.Time
	NonceString string
}

type Session struct {
	ID        int32
	CreatedAt time.Time
	TokenID   uuid.UUID
	UserID    int32
}

type User struct {
	ID        int32
	CreatedAt time.Time
	SteamID   string
}
