// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: openid.sql

package query

import (
	"context"
	"time"
)

const insertNonce = `-- name: InsertNonce :exec
insert into openid_nonce (endpoint, nonce_time, nonce_string) values ($1, $2, $3)
`

type InsertNonceParams struct {
	Endpoint    string
	NonceTime   time.Time
	NonceString string
}

func (q *Queries) InsertNonce(ctx context.Context, arg InsertNonceParams) error {
	_, err := q.db.Exec(ctx, insertNonce, arg.Endpoint, arg.NonceTime, arg.NonceString)
	return err
}
