// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user.sql

package query

import (
	"context"

	"github.com/google/uuid"
)

const addSession = `-- name: AddSession :one
with target_user as (
    select u.id from users u where u.steam_id = ($1)
)
insert into session (user_id)
select tu.id from target_user tu
returning id, created_at, token_id, user_id
`

func (q *Queries) AddSession(ctx context.Context, steamID string) (Session, error) {
	row := q.db.QueryRow(ctx, addSession, steamID)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.TokenID,
		&i.UserID,
	)
	return i, err
}

const addUserIgnoreConflict = `-- name: AddUserIgnoreConflict :exec
insert into users (steam_id)
values ($1)
on conflict (steam_id) do nothing
`

func (q *Queries) AddUserIgnoreConflict(ctx context.Context, steamID string) error {
	_, err := q.db.Exec(ctx, addUserIgnoreConflict, steamID)
	return err
}

const disallowToken = `-- name: DisallowToken :exec
insert into disallow_token (token_id) values ($1)
`

func (q *Queries) DisallowToken(ctx context.Context, tokenID uuid.UUID) error {
	_, err := q.db.Exec(ctx, disallowToken, tokenID)
	return err
}

const findUserBySteamID = `-- name: FindUserBySteamID :one
select id, created_at, steam_id from users where users.steam_id = $1 limit 1
`

func (q *Queries) FindUserBySteamID(ctx context.Context, steamID string) (User, error) {
	row := q.db.QueryRow(ctx, findUserBySteamID, steamID)
	var i User
	err := row.Scan(&i.ID, &i.CreatedAt, &i.SteamID)
	return i, err
}

const getDisallowToken = `-- name: GetDisallowToken :one
select exists(select token_id, created_at from disallow_token where token_id = $1)
`

func (q *Queries) GetDisallowToken(ctx context.Context, tokenID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getDisallowToken, tokenID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
